# Pipeline to build and deploy Dedicated SQL pool for Synapse Data Platform https://github.com/bennyaustin/synapse-dataplatform implemented using ELT Framework https://github.com/bennyaustin/elt-framework

trigger:
- main

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
  vmImage: windows-latest

steps:
- task: VSBuild@1
  displayName: Build database project
  inputs:
    solution: '**\dw01.sln'

- publish: $(System.DefaultWorkingDirectory)
  artifact: dacpac
  displayName: Publish Dacpac

- task: AzureKeyVault@2
  displayName: Get keyvault secrets
  inputs:
    connectedServiceName: ba-devops-spn
    KeyVaultName: ba-keyvault1 
    SecretsFilter: dw01-sqlusername,dw01-sqlpassword
    RunAsPreJob: true
- task: SqlAzureDacpacDeployment@1
  displayName: Deploy database
  inputs:
    ConnectedServiceNameARM: ba-devops-spn
    AuthenticationType: server
    ServerName: ba-synapseanalytics01.sql.azuresynapse.net,1433
    DatabaseName: dw01
    SqlUsername: $(dw01-sqlusername)
    SqlPassword: $(dw01-sqlpassword)
    DacpacFile: dedicated-sqlpools\dw01\bin\Release\dw01.dacpac
    IpDetectionMethod: AutoDetect
    DeleteFirewallRule: true
    AdditionalArguments: /p:DropPermissionsNotInSource=false /p:DropRoleMembersNotInSource=false /p:DropObjectsNotInSource=true /p:IgnoreColumnOrder=true /p:IgnorePermissions=true /v:DatalakeEndpoint="bastoragedatalake01.dfs.core.windows.net"